5814 - migrate travel sensors to atd-knack-services
cityofaustin/atd-knack-services pull request #70
Opened 2021-04-19 18:26 UTC by chiaberry

**Issue**: https://github.com/cityofaustin/atd-data-tech/issues/5814

Adds the configuration for travel-sensors

Here is the corresponding airflow PR: cityofaustin/atd-airflow#
Corresponding atd-data-deploy PR: cityofaustin/atd-data-deploy#

**socrata:** https://data.austintexas.gov/Transportation-and-Mobility/Travel-Sensors/6yd9-yz2
**agol:** https://austin.maps.arcgis.com/home/item.html?id=9776d3e894a74521a7f63443f7becc7c
**knack:** https://atd.knack.com/amd#signal-queries/travel-sensors/

2021-04-20 21:44 UTC, chiaberry commented
@johnclary I was trying to think if there would be a scenario where we would want to be able to toggle the field removal, but then i remembered that if you dont remove the fields it fails.

2021-04-21 14:04 UTC, johnclary requested changes

2021-04-21 14:04 UTC, johnclary commented on services/records_to_socrata.py
> +    columnNames = [c["fieldName"] for c in client_metadata["columns"]]
`column_names` > `columnNames`

2021-04-21 14:04 UTC, johnclary commented on services/records_to_socrata.py
> +    return payload
since you're modifying payload in place, the behavior will be more clear if this function returns nothing.

2021-04-21 14:04 UTC, johnclary commented on services/records_to_socrata.py
> +    unknown_fields = [fieldName.lower() for fieldName in record_fieldNames if fieldName.lower() not in columnNames]
looks great! at this stage in the ETL you should not need the case checking with `.lower()`. the field names should exactly match, and if they don't the socrata pub will fail, i think?

2021-04-21 14:04 UTC, johnclary commented on services/records_to_socrata.py
> +    return payload
we should return before line 55 if there are no unknown fieldnames. then we don't have to waste time iterating through the record payload.

2021-04-21 14:15 UTC, chiaberry commented on services/records_to_socrata.py
> +    unknown_fields = [fieldName.lower() for fieldName in record_fieldNames if fieldName.lower() not in columnNames]
The payload's field names are all lower case at this point, but i pulled the names from the records pre-formatting on line 150 `records[0].names()` and they are uppercase there.

2021-04-21 14:23 UTC, chiaberry commented on services/records_to_socrata.py
> +    return payload
gotcha, i initially wasn't going to return the payload, then saw the function above `bools_to_strings(records)` returns the payload and waffled on my initial instinct. fixed it now.

2021-04-21 15:06 UTC, johnclary commented on services/records_to_socrata.py
> +    return payload
that would be my bad. you mind removing that return payload from `bools_to_strings()`?

2021-04-21 22:53 UTC, johnclary commented on services/records_to_socrata.py
> +    if len(unknown_fields) > 0:
this is fine, but more Pythonic would be simply `if unknown_fields:`. Empty lists and dicts are falsey in Python.

2021-04-21 22:54 UTC, johnclary approved these changes
nice work! this is a really nice enhancement. 🚢

2021-04-21 22:56 UTC, johnclary commented
@chiaberry might be worth adding a note about this functionality in [this section of the docs](https://github.com/cityofaustin/atd-knack-services#publish-records-to-the-open-data-portal)? have you found these docs helpful?

2021-04-21 23:20 UTC, chiaberry commented
The docs are super helpful, I actually have a section of it printed out so I can easily reference it. I updated the README with a line about the update.

2021-04-22 14:35 UTC, merged

2021-04-22 17:16 UTC, johnclary commented on services/records_to_socrata.py
> +    remove_unknown_fields(records[0].names(), payload, metadata_socrata)
hmm—I'm not sure we want to use `records[0].names()` names here. The payload's record keys are transformed above in `format_keys(payload)`, and so the payload's keys at this point should exactly match the Socrata column names. 

I think you can just pass `payload[0].keys()` instead?